export const copy = {
  uz: {
    delivery: "Yetkazib berish xaridor tomonidan to‘lanadi",
    home: "Bosh sahifa",
    products: "Mahsulotlar",
    builder: "O‘z dizayningizni yarating",
    about: "Biz haqimizda",
    reviews: "Otzivlar",
    contact: "Aloqa",
    order: "Buyurtma berish",
    menu: "Menyu",
    eyebrow: "Sokin fikrlar uchun",
    titleA: "Qo‘lda yaratilgan",
    titleB: "kundaliklar.",
    heroText: "Har bir jurnal 100% qo‘l mehnati bilan, barcha detallariga e’tibor berib, aynan siz uchun tayyorlanadi.",
    limited: "Har bir kundalik cheklangan nusxada chiqariladi",
    view: "Mahsulotlarni ko‘rish",
    collection: "KUNDALIKLAR",
    collectionText: "Kundalik foydalanish, sayohat va sovg‘a uchun puxta ishlangan modellar.",
    choose: "Tanlash",
    design: "O‘Z DIZAYNINGIZNI YARATING",
    designText: "Model, charm, ip va qog‘oz turini tanlang. Narx va buyurtma xulosasi avtomatik yangilanadi.",
    size: "O‘lcham",
    leather: "Charm rangi",
    thread: "Ip rangi",
    paper: "Qog‘oz turi",
    summary: "Tanlangan konfiguratsiya",
    price: "Narx",
    add: "Savatchaga qo‘shish",
    cart: "Savatcha",
    empty: "Savatcha hozircha bo‘sh",
    emptyHint: "Mahsulot tanlang yoki o‘z dizayningizni yarating.",
    total: "Jami",
    checkout: "Buyurtmani rasmiylashtirish",
    remove: "Olib tashlash",
    quantity: "Soni",
    checkoutTitle: "Buyurtma ma’lumotlari",
    checkoutText: "Ma’lumotlarni to‘ldiring. Tayyor buyurtma matni @thatswriter chatida ochiladi.",
    name: "Ism",
    phone: "Telefon raqami",
    city: "Shahar / viloyat",
    address: "Aniq manzil",
    comment: "Qo‘shimcha izoh",
    required: "Ism, telefon raqami va shaharni kiriting.",
    send: "Telegram orqali yuborish",
    close: "Yopish",
    cream: "Krem",
    lined: "Chiziqli",
    dotted: "Nuqtali",
    from: "dan",
    added: "Savatchaga qo‘shildi",
    storyEyebrow: "SEKIN VA PUXTA YARATILADI",
    storyTitle: "Har kuni qo‘lga olishni istaydigan kundalik.",
    storyText: "Silent Script kundaligi oddiy bloknot emas. U kundalik rejalaringiz, muhim fikrlaringiz va xotiralaringiz bilan birga vaqt o‘tishi davomida o‘ziga xos ko‘rinish hosil qiladi.",
    storyPoint1: "Qalin va uzoq xizmat qiladigan charm",
    storyPoint2: "Almashtiriladigan ichki daftar",
    storyPoint3: "Buyurtma asosida qo‘lda tayyorlash",
    processEyebrow: "BUYURTMA JARAYONI",
    processTitle: "Oddiy, tushunarli va shaffof.",
    step1Title: "Modelni tanlang",
    step1Text: "Katalogdan tayyor modelni tanlang yoki konfiguratorni oching.",
    step2Title: "Moslashtiring",
    step2Text: "Charm rangi, ip va qog‘oz turini o‘zingizga moslang.",
    step3Title: "Telegramda tasdiqlang",
    step3Text: "Buyurtma xulosasi @thatswriter chatiga tayyor xabar bo‘lib yuboriladi.",
    reviewsEyebrow: "MIJOZLAR FIKRI",
    reviewsTitle: "Kundalikni ishlatganlarning taassurotlari.",
    review1: "Charm sifati va tikuvlari juda puxta. Kundalikni qo‘lga olganda haqiqatan premium his beradi.",
    review2: "Rangni va ipni o‘zim tanladim. Tayyor mahsulot tasavvur qilganimdan ham chiroyli chiqdi.",
    review3: "Sovg‘a uchun buyurtma qilgandim. Qadoqlanishi ham, mahsulotning o‘zi ham juda didli.",
    faqEyebrow: "SAVOLLAR",
    faqTitle: "Buyurtmadan oldin bilishingiz kerak bo‘lganlar.",
    faq1q: "Tayyorlash qancha vaqt oladi?",
    faq1a: "Muddat model va buyurtmalar soniga bog‘liq. Aniq muddat Telegram orqali tasdiqlanadi.",
    faq2q: "Yetkazib berish narxga kiradimi?",
    faq2a: "Yo‘q. Yetkazib berish xaridor tomonidan alohida to‘lanadi.",
    faq3q: "Rang va ipni o‘zim tanlay olamanmi?",
    faq3a: "Ha. Konfigurator orqali mavjud charm, ip va qog‘oz variantlarini tanlashingiz mumkin.",
    faq4q: "Buyurtmani qaytarish yoki almashtirish mumkinmi?",
    faq4a: "Mahsulotlar buyurtma asosida tayyorlanadi. Ish boshlanishidan oldin barcha detallar Telegramda tasdiqlanadi.",
    policyTitle: "Buyurtma, to‘lov va yetkazib berish",
    policyText: "Buyurtma Telegram orqali tasdiqlanadi. To‘lov va tayyorlash tafsilotlari alohida kelishiladi. Yetkazib berish xaridor hisobidan.",
    ctaTitle: "Sizning fikrlaringiz uchun yaratilgan kundalik.",
    ctaText: "Modelni tanlang, o‘zingizga moslang va buyurtmani bir necha daqiqada yuboring.",
    ctaButton: "Dizayn yaratish",
    footerText: "Qo‘lda tayyorlangan charm kundaliklar. Sokin fikrlar, rejalar va xotiralar uchun.",
    rights: "Barcha huquqlar himoyalangan.",
  },
  ru: {
    delivery: "Доставку оплачивает покупатель",
    home: "Главная",
    products: "Товары",
    builder: "Создать свой дизайн",
    about: "О нас",
    reviews: "Отзывы",
    contact: "Контакты",
    order: "Оформить заказ",
    menu: "Меню",
    eyebrow: "Для спокойных мыслей",
    titleA: "Кожаные ежедневники",
    titleB: "ручной работы.",
    heroText: "Каждый ежедневник полностью создаётся вручную, с вниманием к деталям и специально для вас.",
    limited: "Каждый ежедневник выпускается ограниченным тиражом",
    view: "Смотреть товары",
    collection: "ЕЖЕДНЕВНИКИ",
    collectionText: "Продуманные модели для ежедневных записей, путешествий и подарков.",
    choose: "Выбрать",
    design: "СОЗДАЙТЕ СВОЙ ДИЗАЙН",
    designText: "Выберите модель, кожу, нить и бумагу. Цена и итог заказа обновляются автоматически.",
    size: "Размер",
    leather: "Цвет кожи",
    thread: "Цвет нити",
    paper: "Тип бумаги",
    summary: "Выбранная конфигурация",
    price: "Цена",
    add: "Добавить в корзину",
    cart: "Корзина",
    empty: "Корзина пока пуста",
    emptyHint: "Выберите товар или создайте собственный дизайн.",
    total: "Итого",
    checkout: "Оформить заказ",
    remove: "Удалить",
    quantity: "Количество",
    checkoutTitle: "Данные заказа",
    checkoutText: "Заполните данные. Готовый текст заказа откроется в чате @thatswriter.",
    name: "Имя",
    phone: "Номер телефона",
    city: "Город / область",
    address: "Точный адрес",
    comment: "Комментарий",
    required: "Укажите имя, номер телефона и город.",
    send: "Отправить через Telegram",
    close: "Закрыть",
    cream: "Кремовая",
    lined: "В линейку",
    dotted: "В точку",
    from: "от",
    added: "Добавлено в корзину",
    storyEyebrow: "СОЗДАЁТСЯ МЕДЛЕННО И ТЩАТЕЛЬНО",
    storyTitle: "Ежедневник, который хочется брать в руки каждый день.",
    storyText: "Silent Script — не просто блокнот. Со временем кожа меняется вместе с вашими планами, важными мыслями и воспоминаниями, приобретая уникальный характер.",
    storyPoint1: "Плотная и долговечная кожа",
    storyPoint2: "Сменный внутренний блокнот",
    storyPoint3: "Ручная работа под заказ",
    processEyebrow: "КАК ЗАКАЗАТЬ",
    processTitle: "Просто, понятно и прозрачно.",
    step1Title: "Выберите модель",
    step1Text: "Откройте готовую модель в каталоге или используйте конфигуратор.",
    step2Title: "Настройте детали",
    step2Text: "Выберите цвет кожи, нить и тип бумаги.",
    step3Title: "Подтвердите в Telegram",
    step3Text: "Готовое описание заказа откроется сообщением в чате @thatswriter.",
    reviewsEyebrow: "ОТЗЫВЫ",
    reviewsTitle: "Впечатления тех, кто уже пользуется ежедневником.",
    review1: "Качество кожи и швов очень аккуратное. Ежедневник действительно ощущается премиальным.",
    review2: "Я сама выбрала цвет и нить. Готовая работа оказалась ещё красивее, чем я представляла.",
    review3: "Заказывала в подарок. И упаковка, и сам ежедневник выглядят очень стильно.",
    faqEyebrow: "ВОПРОСЫ",
    faqTitle: "Что нужно знать перед заказом.",
    faq1q: "Сколько времени занимает изготовление?",
    faq1a: "Срок зависит от модели и текущей очереди. Точная дата подтверждается в Telegram.",
    faq2q: "Доставка входит в стоимость?",
    faq2a: "Нет. Доставку покупатель оплачивает отдельно.",
    faq3q: "Можно выбрать цвет кожи и нити?",
    faq3a: "Да. В конфигураторе можно выбрать доступную кожу, нить и тип бумаги.",
    faq4q: "Можно вернуть или обменять заказ?",
    faq4a: "Изделия создаются под заказ. Все детали подтверждаются в Telegram до начала работы.",
    policyTitle: "Заказ, оплата и доставка",
    policyText: "Заказ подтверждается в Telegram. Оплата и сроки согласовываются отдельно. Доставку оплачивает покупатель.",
    ctaTitle: "Ежедневник, созданный для ваших мыслей.",
    ctaText: "Выберите модель, настройте детали и отправьте заказ за несколько минут.",
    ctaButton: "Создать дизайн",
    footerText: "Кожаные ежедневники ручной работы для спокойных мыслей, планов и воспоминаний.",
    rights: "Все права защищены.",
  },
} as const;
