export const ui = {
  uz: {
    currency: "so‘m",
    announcement: "Qo‘lda tayyorlanadigan charm kundaliklar",
    announcementNote: "Buyurtma Telegram orqali tasdiqlanadi",
    home: "Bosh sahifa",
    shop: "Katalog",
    builder: "Konstruktor",
    about: "Nega biz?",
    processNav: "Buyurtma",
    contact: "Aloqa",
    menu: "Menyu",
    cart: "Savat",
    heroEyebrow: "SIZ UCHUN YARATILGAN",
    heroTitle: "Qo‘lda yaratilgan charm kundaliklar.",
    heroText: "Yozuvlaringiz, rejalaringiz va muhim fikrlaringiz uchun uzoq xizmat qiladigan, shaxsiylashtirilgan kundaliklar.",
    browse: "Katalogni ko‘rish",
    create: "O‘z kundaligingizni yarating",
    heroMeta: ["Tabiiy charm", "A5 va A6 format", "Shaxsiy harf"],
    heroProduct: "Tanlangan model",
    trust: [
      ["100% tabiiy charm", "Har bir g‘ilof tabiiy teksturasi bilan o‘ziga xos."],
      ["Qo‘l mehnati", "Detallar buyurtma asosida ehtiyotkorlik bilan tayyorlanadi."],
      ["Shaxsiy dizayn", "Rang, sahifa turi va muqova harfini o‘zingiz tanlaysiz."],
      ["Sovg‘aga tayyor", "Sovg‘a qutisi va personalizatsiya qo‘shish mumkin."],
    ],
    catalogEyebrow: "SILENT COLLECTION",
    catalogTitle: "Sizga mos modelni tanlang.",
    catalogText: "Charm kundaliklar, almashtiriladigan ichki daftarlar va sovg‘a to‘plamlari.",
    all: "Barchasi",
    cover: "Charm kundaliklar",
    notebook: "Ichki daftarlar",
    set: "To‘plamlar",
    from: "dan",
    details: "Batafsil",
    colors: "rang",
    builderEyebrow: "KUNDALIK KONSTRUKTORI",
    builderTitle: "Bir necha qadamda o‘zingiznikini yarating.",
    builderText: "Modelni tanlang, charm rangini va ichki sahifalarni moslang. Narx har bir tanlov bilan avtomatik yangilanadi.",
    builderSteps: [
      ["Modelni tanlang", "A5 yoki A6 kundalik modelini tanlang."],
      ["Moslashtiring", "Rang, sahifa turi, harf va sovg‘a qutisini belgilang."],
      ["Buyurtma bering", "Tayyor buyurtma Telegramga aniq formatda yuboriladi."],
    ],
    start: "Yaratishni boshlash",
    storyEyebrow: "SEKIN YARATILGAN BUYUMLAR",
    storyTitle: "Bir g‘ilof. Ko‘p yangi sahifalar.",
    storyText: "Ichki daftar tugagach, charm g‘ilof siz bilan qoladi. Faqat refillni almashtirasiz. Vaqt o‘tishi bilan charm yumshaydi va o‘ziga xos patina hosil qiladi.",
    storyLink: "Charm kundaliklarni ko‘rish",
    processEyebrow: "BUYURTMA JARAYONI",
    processTitle: "Oddiy va tushunarli.",
    process: [
      ["Tanlang", "Katalogdan modelni oching yoki konstruktor orqali moslashtiring."],
      ["Tasdiqlang", "Savatdagi tanlovlar, narx va aloqa ma’lumotlarini tekshiring."],
      ["Telegramga yuboring", "Buyurtma @thatswriter akkauntiga tayyor xabar ko‘rinishida boradi."],
    ],
    faqEyebrow: "FAQ",
    faqTitle: "Ko‘p so‘raladigan savollar.",
    faq: [
      ["Buyurtma qanday beriladi?", "Mahsulotni moslab savatga qo‘shing, aloqa ma’lumotlarini kiriting va tayyor buyurtmani Telegram orqali yuboring."],
      ["Muqovaga harf tushirish mumkinmi?", "Ha. Hozircha bitta bosh harf qo‘shish mumkin. Harfning joylashuvi buyurtma tasdiqlanganda kelishiladi."],
      ["Ichki daftarni keyin almashtirish mumkinmi?", "Ha. Charm g‘ilof qayta ishlatiladi, mos A5 yoki A6 refillni alohida almashtirish mumkin."],
      ["Yetkazib berish qancha vaqt oladi?", "Muddat manzil va buyurtma turiga qarab Telegramda tasdiqlanadi."],
    ],
    footerText: "Xotirjam fikrlar uchun qo‘lda tayyorlangan charm kundaliklar va refill bloknotlar.",
    footerShop: "Do‘kon",
    footerHelp: "Yordam",
    footerBrand: "Brend",
    channel: "Telegram kanal",
    admin: "Admin panel",
    rights: "Barcha huquqlar himoyalangan.",
    color: "Charm rangi",
    insert: "Ichki daftar",
    yesInsert: "Daftar bilan",
    noInsert: "Faqat g‘ilof",
    page: "Sahifa turi",
    pages: { lined: "Chiziqli", dotted: "Nuqtali", grid: "Katakli", blank: "Oq" },
    initial: "Muqovadagi harf",
    initialHint: "Bitta harf, ixtiyoriy.",
    gift: "Sovg‘a qutisi",
    yes: "Ha",
    no: "Yo‘q",
    add: "Savatga qo‘shish",
    total: "Jami",
    empty: "Savatingiz hozircha bo‘sh.",
    emptyText: "Katalogdan mahsulot tanlang yoki o‘zingiznikini yarating.",
    remove: "Olib tashlash",
    checkout: "Buyurtmani rasmiylashtirish",
    name: "Ismingiz",
    phone: "Telefon raqamingiz",
    address: "Yetkazib berish manzili",
    comment: "Qo‘shimcha izoh",
    required: "Ism va telefon raqamini kiriting.",
    send: "Telegramga yuborish",
    close: "Yopish",
    orderTitle: "Buyurtmani yakunlang",
    orderText: "Ma’lumotlarni tekshiring. Tugma bosilganda tayyor buyurtma @thatswriter chatida ochiladi.",
    greeting: "Assalomu alaykum! Silent Script’dan quyidagi buyurtmani bermoqchiman:",
    onlyCover: "faqat g‘ilof",
    withInsert: "ichki daftar bilan",
  },
  en: {
    currency: "UZS",
    announcement: "Handcrafted leather journals",
    announcementNote: "Orders are confirmed via Telegram",
    home: "Home",
    shop: "Catalog",
    builder: "Customizer",
    about: "Why us",
    processNav: "How to order",
    contact: "Contact",
    menu: "Menu",
    cart: "Cart",
    heroEyebrow: "MADE FOR YOU",
    heroTitle: "Handcrafted leather journals.",
    heroText: "Personalized journals designed to hold your notes, plans and important thoughts for years.",
    browse: "Explore catalog",
    create: "Create your journal",
    heroMeta: ["Natural leather", "A5 and A6 sizes", "Personal initial"],
    heroProduct: "Featured model",
    trust: [
      ["Natural leather", "Every cover has its own genuine grain and character."],
      ["Hand-finished", "Each detail is carefully prepared to order."],
      ["Made personal", "Choose the colour, page style and cover initial."],
      ["Gift ready", "Add personalisation and a presentation box."],
    ],
    catalogEyebrow: "SILENT COLLECTION",
    catalogTitle: "Find the journal that fits you.",
    catalogText: "Leather journals, replaceable inserts and thoughtful gift sets.",
    all: "All",
    cover: "Leather journals",
    notebook: "Notebook inserts",
    set: "Gift sets",
    from: "from",
    details: "View details",
    colors: "colours",
    builderEyebrow: "JOURNAL CUSTOMIZER",
    builderTitle: "Create your own in a few clear steps.",
    builderText: "Choose a model, leather colour and inner pages. The price updates automatically with every selection.",
    builderSteps: [
      ["Choose a model", "Select an A5 or A6 journal."],
      ["Personalize it", "Pick the colour, pages, initial and gift box."],
      ["Place the order", "Your selections are formatted into a clear Telegram message."],
    ],
    start: "Start customizing",
    storyEyebrow: "MADE SLOWLY",
    storyTitle: "One cover. Many new pages.",
    storyText: "When the insert is full, the leather cover stays with you. Replace only the refill. Over time the leather softens and develops a patina that is uniquely yours.",
    storyLink: "Explore leather journals",
    processEyebrow: "HOW TO ORDER",
    processTitle: "Simple from start to finish.",
    process: [
      ["Choose", "Open a product from the catalog or begin with the customizer."],
      ["Review", "Check your options, total and contact details."],
      ["Send on Telegram", "The complete order opens in the @thatswriter chat."],
    ],
    faqEyebrow: "FAQ",
    faqTitle: "Common questions.",
    faq: [
      ["How do I place an order?", "Customize a product, add it to your cart, enter your contact details and send the ready order through Telegram."],
      ["Can I add an initial?", "Yes. One cover initial is currently available. Placement is confirmed before production."],
      ["Can the notebook be replaced later?", "Yes. Keep the leather cover and replace it with a compatible A5 or A6 refill."],
      ["How long does delivery take?", "Timing is confirmed on Telegram based on your location and order type."],
    ],
    footerText: "Handcrafted leather journals and replaceable notebook inserts for calm, focused writing.",
    footerShop: "Shop",
    footerHelp: "Help",
    footerBrand: "Brand",
    channel: "Telegram channel",
    admin: "Admin panel",
    rights: "All rights reserved.",
    color: "Leather colour",
    insert: "Notebook insert",
    yesInsert: "With insert",
    noInsert: "Cover only",
    page: "Page style",
    pages: { lined: "Lined", dotted: "Dotted", grid: "Grid", blank: "Blank" },
    initial: "Cover initial",
    initialHint: "One letter, optional.",
    gift: "Gift box",
    yes: "Yes",
    no: "No",
    add: "Add to cart",
    total: "Total",
    empty: "Your cart is empty.",
    emptyText: "Choose a product from the catalog or create your own.",
    remove: "Remove",
    checkout: "Continue to order",
    name: "Your name",
    phone: "Phone number",
    address: "Delivery address",
    comment: "Additional note",
    required: "Enter your name and phone number.",
    send: "Send on Telegram",
    close: "Close",
    orderTitle: "Complete your order",
    orderText: "Review your details. The button opens the complete order in the @thatswriter chat.",
    greeting: "Hello! I would like to place the following Silent Script order:",
    onlyCover: "cover only",
    withInsert: "with notebook insert",
  },
  ru: {
    currency: "сум",
    announcement: "Кожаные журналы ручной работы",
    announcementNote: "Заказы подтверждаются в Telegram",
    home: "Главная",
    shop: "Каталог",
    builder: "Конструктор",
    about: "Почему мы",
    processNav: "Как заказать",
    contact: "Контакты",
    menu: "Меню",
    cart: "Корзина",
    heroEyebrow: "СОЗДАНО ДЛЯ ВАС",
    heroTitle: "Кожаные журналы ручной работы.",
    heroText: "Персонализированные журналы для заметок, планов и важных мыслей, которые будут служить годами.",
    browse: "Открыть каталог",
    create: "Создать свой журнал",
    heroMeta: ["Натуральная кожа", "Форматы A5 и A6", "Личная буква"],
    heroProduct: "Выбранная модель",
    trust: [
      ["Натуральная кожа", "Каждая обложка имеет уникальную фактуру и характер."],
      ["Ручная работа", "Каждая деталь аккуратно готовится под заказ."],
      ["Ваш дизайн", "Выберите цвет, страницы и букву на обложке."],
      ["Готово для подарка", "Можно добавить персонализацию и подарочную коробку."],
    ],
    catalogEyebrow: "SILENT COLLECTION",
    catalogTitle: "Найдите свой журнал.",
    catalogText: "Кожаные журналы, сменные блокноты и подарочные наборы.",
    all: "Все",
    cover: "Кожаные журналы",
    notebook: "Сменные блокноты",
    set: "Наборы",
    from: "от",
    details: "Подробнее",
    colors: "цвета",
    builderEyebrow: "КОНСТРУКТОР ЖУРНАЛА",
    builderTitle: "Создайте свой вариант за несколько шагов.",
    builderText: "Выберите модель, цвет кожи и страницы. Цена обновляется автоматически при каждом выборе.",
    builderSteps: [
      ["Выберите модель", "Выберите журнал формата A5 или A6."],
      ["Настройте", "Укажите цвет, страницы, букву и подарочную коробку."],
      ["Оформите заказ", "Все параметры формируются в понятное сообщение Telegram."],
    ],
    start: "Начать настройку",
    storyEyebrow: "СОЗДАНО НЕ СПЕША",
    storyTitle: "Одна обложка. Много новых страниц.",
    storyText: "Когда блокнот заполнится, кожаная обложка останется с вами. Замените только внутренний блок. Со временем кожа становится мягче и приобретает уникальную патину.",
    storyLink: "Смотреть кожаные журналы",
    processEyebrow: "КАК ЗАКАЗАТЬ",
    processTitle: "Просто и понятно.",
    process: [
      ["Выберите", "Откройте товар из каталога или начните с конструктора."],
      ["Проверьте", "Проверьте параметры, итоговую цену и контакты."],
      ["Отправьте в Telegram", "Готовый заказ откроется в чате @thatswriter."],
    ],
    faqEyebrow: "FAQ",
    faqTitle: "Частые вопросы.",
    faq: [
      ["Как оформить заказ?", "Настройте товар, добавьте его в корзину, укажите контакты и отправьте готовый заказ через Telegram."],
      ["Можно добавить букву?", "Да. Сейчас доступна одна буква на обложке. Расположение подтверждается перед изготовлением."],
      ["Можно заменить блокнот позже?", "Да. Кожаная обложка остаётся, а внутренний блок A5 или A6 можно заменить."],
      ["Сколько занимает доставка?", "Срок подтверждается в Telegram в зависимости от города и типа заказа."],
    ],
    footerText: "Кожаные журналы ручной работы и сменные блокноты для спокойных и сосредоточенных записей.",
    footerShop: "Магазин",
    footerHelp: "Помощь",
    footerBrand: "Бренд",
    channel: "Telegram-канал",
    admin: "Админ-панель",
    rights: "Все права защищены.",
    color: "Цвет кожи",
    insert: "Сменный блокнот",
    yesInsert: "С блокнотом",
    noInsert: "Только обложка",
    page: "Тип страниц",
    pages: { lined: "Линейка", dotted: "Точки", grid: "Клетка", blank: "Чистые" },
    initial: "Буква на обложке",
    initialHint: "Одна буква, необязательно.",
    gift: "Подарочная коробка",
    yes: "Да",
    no: "Нет",
    add: "Добавить в корзину",
    total: "Итого",
    empty: "Корзина пока пуста.",
    emptyText: "Выберите товар в каталоге или создайте свой вариант.",
    remove: "Удалить",
    checkout: "Оформить заказ",
    name: "Ваше имя",
    phone: "Номер телефона",
    address: "Адрес доставки",
    comment: "Комментарий",
    required: "Введите имя и номер телефона.",
    send: "Отправить в Telegram",
    close: "Закрыть",
    orderTitle: "Завершите заказ",
    orderText: "Проверьте данные. Кнопка откроет готовый заказ в чате @thatswriter.",
    greeting: "Здравствуйте! Хочу оформить следующий заказ Silent Script:",
    onlyCover: "только обложка",
    withInsert: "со сменным блокнотом",
  },
} as const;
